Track upstream maven-site-plugin.
Reported by dblanch: mvn site site:stage  can fail in newer Maven
versions, with java.lang.NoClassDefFoundError:
org/sonatype/aether/graph/DependencyFilter

The explanation is here:
https://cwiki.apache.org/confluence/display/MAVEN/AetherClassNotFound

Solution requires updating to maven-site-plugin >= 3.3.  3.4 is current
and works for me, so it is now specified.